### ISSUE TITLE
BiocParallel fails after using read_csv

### ISSUE THREAD

**Issue by pfh** [tidyverse/readr#1170]
After using `read_csv`, Bioconductor parallel processing fails. I am using R 4.0.3, Bioconductor 3.12, readr 1.4.0.

```r
readr::read_csv("a,b\n1.0,2.0") 
BiocParallel::bpstart() 
BiocParallel::bplapply(list(1,2,3,4), identity)
```

`bplapply` fails. I have tried this on Mac OS and Linux and it fails on both platforms. Mac OS output is shown below.

Does not fail if `read_csv` step is omitted. Does not fail if the `bpstart` step is omitted. 

```
> readr::read_csv("a,b\n1.0,2.0")
# A tibble: 1 x 2
      a     b
  <dbl> <dbl>
1     1     2
> BiocParallel::bpstart()
> BiocParallel::bplapply(list(1,2,3,4), identity)
Error: C stack usage  7969408 is too close to the limit
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] fansi_0.4.1         utf8_1.1.4          crayon_1.3.4
 [4] assertthat_0.2.1    R6_2.5.0            lifecycle_0.2.0
 [7] magrittr_2.0.1      pillar_1.4.7        rlang_0.4.10
[10] cli_2.2.0           vctrs_0.3.6         ellipsis_0.3.1
[13] BiocParallel_1.24.1 tools_4.0.3         readr_1.4.0
[16] glue_1.4.2          hms_0.5.3           parallel_4.0.3
[19] compiler_4.0.3      pkgconfig_2.0.3     tibble_3.0.4
>
```

**Comment by jimhester** [comment]
Thanks, I can reproduce this, I will try to figure out where the stack is being corrupted.

**Comment by jimhester** [comment]
So this seems to be fixed by using the devel version of cpp11 and recompiling readr. I will submit a new version of cpp11 to CRAN which should resolve this.

**Comment by jimhester** [comment]
This should now be fixed with the latest CRAN version of cpp11, if you find this is not the case we can re-open this.

**Comment by pfh** [comment]
Thank you!

After updating cpp11 from CRAN: The binary version that installed by `install.packages("readr")` on Mac OS is still broken. If I install from source with with `install.packages("readr", type="source")` it is fixed.

**Comment by jimhester** [comment]
CRAN should rebuild the readr binary in the next few days
