### ISSUE TITLE
write_csv is causing fatal error on R

### ISSUE THREAD

**Issue by rbufba** [tidyverse/readr#1314]
Hello. I'm doing some manipulations on a database and in the end trying to save with write_csv and this is generating a fatal error in R. I tried to paste the reprex below. When I use write.csv I can save the database without any problems.

I can also save other databases as mtcars for example (write_csv(mtcars, "data/mtcars.csv") The problem seems to me to be with this specific database attached. It concerns the population size of Brazilian municipalities.

This reprex appears to crash R.
See standard output and standard error for more details.

#### Standard output and error

``` sh
[31mx[39m Install the [34m[34mstyler[34m[39m package in order to use [30m[47m[30m[47m`style = TRUE`[47m[30m[49m[39m.
```

reprex::reprex({
  setwd("C:/Users/rafae/OneDrive/2021.2/Pesquisa/Artigos - Tese/Artigo 1 - RSP")
  pop_mun <- readr::read_csv("data/pop_mun_2002_2019.csv") |> 
  dplyr::mutate(porte_pop = factor(ifelse(pop <=5000, "Até 5000",
                            ifelse(pop > 5000 & pop <= 10000, "De 5.001 até 10.000",
                                   ifelse(pop > 10000 & pop <= 20000, "De 10.001 até 20.000",
                                          ifelse(pop > 20000 & pop <= 50000, "De 20.001 até 50.000",
                                                 ifelse(pop > 50000 & pop <= 100000, "De 50.001 até 100.000",
                                                        ifelse(pop > 100000 & pop <= 500000, "De 100.001 até 500.000",
                                                               ifelse(pop > 500000 , "Maior que 500.000", NA))))))))) |> 
  tidyr::drop_na(porte_pop)

readr::write_csv(pop_mun, "data/teste.csv")
}
,
std_out_err = TRUE)

[pop_mun_2002_2019.csv](https://github.com/tidyverse/readr/files/7314636/pop_mun_2002_2019.csv)

**Comment by aiyanghnL** [comment]
When the form contains Chinese，write more than 20,000 lines， generate a fatal error in R 4.1.1, readr 2.0.2.
![KFEP{ J78EK @56A60A BS](https://user-images.githubusercontent.com/52575545/136728826-043965f3-5000-4ba6-b3f0-0e6ba5bbd47c.jpg)

**Comment by jimhester** [comment]
Please make sure you have the latest version of the vroom package (1.5.5), this should already be fixed there.

**Comment by DiabbZegpi** [comment]
I have the same issue, with spanish accent marks (´). The R bomb appears when writing a 2.2 MB csv. The file still gets written, but when reading in with read_csv and counting some random column, I realize that accents aren't displayed correctly.

My vroom version is 1.5.6.

**Comment by vidarvr** [comment]
Having the same issue.
I have vroom version 1.5.6.9000 and readr version 2.1.0.9000. I have this issue only with large data set (1.8 GB, 10.5 million rows and 14 columns).

**Comment by jimhester** [comment]
@DiabbZegpi and @vidarvr you will have to open a new issue on the vroom repository with a _minimal_ reproducible example to be able for us to reproduce the issue and make progress towards a fix.
