### ISSUE TITLE
parse_datetime crashes on linux

### ISSUE THREAD

**Issue by gifi** [tidyverse/readr#562]
```R
readr::parse_datetime("2001-10-10 20:10", locale = readr::locale(tz = "Pacific/Auckland"))

```
crashes the R process. Neither `readr::parse_datetime` without the `locale` argument nor `readr::locale` have the same behaviour.

```R
R> readr::parse_datetime("2001-10-10 20:10")
[1] "2001-10-10 20:10:00 UTC"

R> readr::locale(tz = "Pacific/Auckland")
<locale>
Numbers:  123,456.78
Formats:  %AD / %AT
Timezone: Pacific/Auckland
Encoding: UTF-8
<date_names>
Days:   Sunday (Sun), Monday (Mon), Tuesday (Tue), Wednesday (Wed), Thursday (Thu), Friday (Fri), Saturday (Sat)
Months: January (Jan), February (Feb), March (Mar), April (Apr), May (May), June (Jun), July (Jul), August (Aug),
        September (Sep), October (Oct), November (Nov), December (Dec)
AM/PM:  AM/PM

R> packageVersion("readr")
[1] ‘1.0.0’

R> readr::parse_datetime("2001-10-10 20:10", locale = readr::locale(tz = "Europe/Dublin"))
Aborted (core dumped)
$
```

The tail of valgrind's outputs:
```Text
==23997== 
==23997== Process terminating with default action of signal 6 (SIGABRT)
==23997==    at 0x7C2B765: raise (in /usr/lib64/libc-2.23.so)
==23997==    by 0x7C2D369: abort (in /usr/lib64/libc-2.23.so)
==23997==    by 0x79E357C: __mulvdi3 (in /usr/lib64/libgcc_s-6.2.1-20160916.so.1)
==23997==    by 0x14DDE53C: time2sub.constprop.11 (localtime.c:1633)
==23997==    by 0x14DDEA40: time1.constprop.8 (localtime.c:1734)
==23997==    by 0x14D919A8: CollectorDateTime::setValue(int, Token const&) (DateTime.h:167)
==23997==    by 0x14DE521B: parse_vector_(Rcpp::Vector<16, Rcpp::PreserveStorage>, Rcpp::Vector<19, Rcpp::PreserveStorage>, Rcpp::Vector<19, Rcpp::PreserveStorage>, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (parse.cpp:132)
==23997==    by 0x14DB2BD0: readr_parse_vector_ (RcppExports.cpp:110)
==23997==    by 0x4AE261: R_doDotCall (dotcode.c:579)
==23997==    by 0x4BB44B: do_dotcall (dotcode.c:1252)
==23997==    by 0x5023E7: Rf_eval (eval.c:723)
==23997==    by 0x529D53: do_begin (eval.c:2291)
```

```R
# The crash is also reproducible with R version 3.3.2 (2016-10-31)
R> sessionInfo()
R Under development (unstable) (2016-11-25 r71694)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Fedora 24 (Workstation Edition)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.4.0
```

**Comment by krlmlr** [comment]
Can't confirm this on Ubuntu 16.10 nor on RedHat 7.2, the following command works on my system without any warnings or errors:

```bash
R -d valgrind -e 'readr::parse_datetime("2001-10-10 20:10", locale = readr::locale(tz = "Pacific/Auckland"))'
```

**Comment by gifi** [comment]
> Can't confirm this on Ubuntu 16.10 nor on RedHat 7.2.

The bug is seen in Fedora 24 as the original post reported in the sessionInfo: _“Running under: Fedora 24 (Workstation Edition).”_

But that's a customized build on that Fedora since it ships with a change I made to overcome #507, otherwise there is no successful build on the system I use. Let's track #507 inside its own thread and forget this one for the time being.

**Comment by jimhester** [comment]
I can't reproduce this on Fedora 24 either with current master (https://github.com/tidyverse/readr/commit/3fd00e30a5122a699ec62a46106a365a1c738caa)

```r
readr::parse_datetime("2001-10-10 20:10", locale = readr::locale(tz = "Pacific/Auckland"))
#> [1] "2001-10-10 20:10:00 NZDT"
```

**Comment by gergness** [comment]
To add to the confusion, I get this crash on my Windows machine.

**Comment by gifi** [comment]
Still, here the story is different, even with `R --vanilla` so that I don't get tripped with dormant customizations.
Might the mismatch coming from different Glibc & GCC versions? Would you see if 

```Bash
printf "%s\n\n" "$(ldd --version)" "$(gcc --version)"
```

outputs

```Text
ldd (GNU libc) 2.23
…
gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)
…
```

**Comment by jimhester** [comment]
Are you sure you are using the latest master, not your PR?

- `ldd (GNU libc) 2.23`
- `gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-2)`
- `clang version 3.8.0 (tags/RELEASE_380/final)`

I don't get a crash with the package compiled with either gcc or clang.

FWIW I am using the rhub fedora docker container [rhub/fedora-clang](https://hub.docker.com/r/rhub/fedora-clang/tags/) if you want to reproduce the results yourself.

**Comment by gifi** [comment]
I have the latest master.

```Bash
cat …/readr/DESCRIPTION
```

```Text
 …
Version: 1.0.0.9000
…
RemoteType: github
RemoteHost: https://api.github.com
RemoteRepo: readr
RemoteUsername: tidyverse
RemoteRef: master
RemoteSha: 3fd00e30a5122a699ec62a46106a365a1c738caa
GithubRepo: readr
GithubUsername: tidyverse
GithubRef: master
GithubSHA1: 3fd00e30a5122a699ec62a46106a365a1c738caa
```

But I see we don't have the same compiler versions.

- `gcc (GCC) 6.3.1 20161221 (Red Hat 6.3.1-1)`
- `clang version 3.8.1 (tags/RELEASE_381/final)`

And I just tested on the latest possible Fedora (aka Rawhide), the bug is now there.

**Comment by jimhester** [comment]
This should be fixed

**Comment by gifi** [comment]
@jimhester 
It seems to be a low priority bug as only one other user faced it, so maybe it's fair to close it on that basis. But it certainly is not fixed.
On Fedora, Clang is not fully supported, there isn't yet a libc++abi package. Let's use the https://hub.docker.com/r/rhub/fedora-gcc/ as a starting point. If that image is upgraded to Rawhide (currently branched as Fedora 26), it will be possible to reproduce the bug. 

**Caveat 1**. It is also reproducible on the Fedora 24 I use, but I can't downgrade installed packages to match the versions in the docker image. That's why I am proposing to work with Rawhide: that way, we'll be able to test on the same configurations.

**Caveat 2**. The last time I reported about Rawhide, GCC was still in the v6 series. Now it has been pushed in the v7 series and is currently incompatible with R (issues between the Fortran compiler and BLAS). So it may be till some days before Rawhide provides for a usable R build.

Aside, I tested with Debian sid and there is no issue. I followed-up with Archlinux and the issue popped up. Looking at the content of the `rhub`, I guess it's kind of moot to bother with Archlinux. So I will let you know the next time Fedora Rawhide build (GCC + R) will be fixed.

**Comment by gifi** [comment]
> So I will let you know the next time Fedora Rawhide build (GCC + R) will be fixed.

I'm back to this now there is a fine Fedora Rawhide compose.

**New logs**
As stated before, nothing has changed since GCC 7 has been introduced

```Text
==2030== Memcheck, a memory error detector
==2030== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==2030== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==2030== Command: /usr/lib64/R/bin/exec/R --vanilla -e readr::parse_datetime("2001-10-10~+~20:10",~+~locale~+~=~+~readr::locale(tz~+~=~+~"Pacific/Auckland"))
==2030== 

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
[snipped]

> readr::parse_datetime("2001-10-10 20:10", locale = readr::locale(tz = "Pacific/Auckland"))

==2030== 
==2030== Process terminating with default action of signal 6 (SIGABRT)
==2030==    at 0x7A497CB: raise (in /usr/lib64/libc-2.25.so)
==2030==    by 0x7A4B5E0: abort (in /usr/lib64/libc-2.25.so)
==2030==    by 0xA04F3FC: __mulvdi3 (in /usr/lib64/libgcc_s-7-20170219.so.1)
==2030==    by 0x110AFB1C: time2sub.constprop.11 (localtime.c:1628)
==2030==    by 0x110AFF6B: time2 (localtime.c:1729)
==2030==    by 0x110AFF6B: time1.constprop.8 (localtime.c:1750)
==2030==    by 0x1105FA68: localtime (DateTime.h:161)
==2030==    by 0x1105FA68: datetime (DateTime.h:96)
==2030==    by 0x1105FA68: CollectorDateTime::setValue(int, Token const&) (Collector.cpp:146)
==2030==    by 0x110B7130: parse_vector_(Rcpp::Vector<16, Rcpp::PreserveStorage>, Rcpp::Vector<19, Rcpp::PreserveStorage>, Rcpp::Vector<19, Rcpp::PreserveStorage>, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) (parse.cpp:132)
==2030==    by 0x1107F508: readr_parse_vector_ (RcppExports.cpp:110)
==2030==    by 0x4F0E4C3: ??? (in /usr/lib64/R/lib/libR.so)
==2030==    by 0x4F4A6BB: Rf_eval (in /usr/lib64/R/lib/libR.so)
==2030==    by 0x4F4CDAC: ??? (in /usr/lib64/R/lib/libR.so)
==2030==    by 0x4F4A48D: Rf_eval (in /usr/lib64/R/lib/libR.so)
[snipped]
```

**Fedora version**
To avoid discrepancies due to different testing environments, my impression is we would better use Rawhide and its current compose is [Fedora-Rawhide-20170220.n.2](https://kojipkgs.fedoraproject.org/compose/rawhide/latest-Fedora-Rawhide/COMPOSE_ID).

```Bash
# cat /etc/os-release 
NAME=Fedora
VERSION="26 (Rawhide)"
ID=fedora
VERSION_ID=26
PRETTY_NAME="Fedora 26 (Rawhide)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:26"
HOME_URL="https://fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
PRIVACY_POLICY_URL=https://fedoraproject.org/wiki/Legal:PrivacyPolicy
```


**readr version**
The tested version is from GitHub, master branch.

```Bash
# tail -11 /usr/lib64/R/library/readr/DESCRIPTION 
Built: R 3.3.2; x86_64-redhat-linux-gnu; 2017-02-21 18:24:00 UTC; unix
RemoteType: github
RemoteHost: https://api.github.com
RemoteRepo: readr
RemoteUsername: tidyverse
RemoteRef: master
RemoteSha: 33f3f3838dc7b0c87524f79bd7d3fcfda12b3192
GithubRepo: readr
GithubUsername: tidyverse
GithubRef: master
GithubSHA1: 33f3f3838dc7b0c87524f79bd7d3fcfda12b3192
```

**GCC version**

```Bash
# gcc --version
gcc (GCC) 7.0.1 20170219 (Red Hat 7.0.1-0.9)
[snipped]
```

This is a bump for @jimhester
